/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author sergi
 */
public class StartMenu extends javax.swing.JFrame {
    
    JFrame frame = new JFrame();

    int xMouse, yMouse;
    
    public StartMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpBg = new javax.swing.JPanel();
        jpTopBar = new javax.swing.JPanel();
        jpExitBtn = new javax.swing.JPanel();
        jlExitText = new javax.swing.JLabel();
        jpMinimizeBtn = new javax.swing.JPanel();
        jlMinimizeText = new javax.swing.JLabel();
        jlImage = new javax.swing.JLabel();
        jpText = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbStartMenu = new javax.swing.JButton();
        jbShowMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpBg.setBackground(new java.awt.Color(255, 255, 255));
        jpBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTopBar.setBackground(new java.awt.Color(255, 255, 204));
        jpTopBar.setPreferredSize(new java.awt.Dimension(500, 40));
        jpTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpTopBarMouseDragged(evt);
            }
        });
        jpTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpTopBarMousePressed(evt);
            }
        });
        jpTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpExitBtn.setBackground(new java.awt.Color(255, 255, 255));

        jlExitText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlExitText.setForeground(new java.awt.Color(255, 51, 51));
        jlExitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExitText.setText("X");
        jlExitText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExitTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlExitTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlExitTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpExitBtnLayout = new javax.swing.GroupLayout(jpExitBtn);
        jpExitBtn.setLayout(jpExitBtnLayout);
        jpExitBtnLayout.setHorizontalGroup(
            jpExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlExitText, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jpExitBtnLayout.setVerticalGroup(
            jpExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlExitText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpTopBar.add(jpExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpMinimizeBtn.setBackground(new java.awt.Color(255, 255, 255));
        jpMinimizeBtn.setForeground(new java.awt.Color(0, 0, 0));
        jpMinimizeBtn.setPreferredSize(new java.awt.Dimension(49, 32));

        jlMinimizeText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMinimizeText.setForeground(new java.awt.Color(0, 0, 0));
        jlMinimizeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizeText.setText("-");
        jlMinimizeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizeTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizeTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizeTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpMinimizeBtnLayout = new javax.swing.GroupLayout(jpMinimizeBtn);
        jpMinimizeBtn.setLayout(jpMinimizeBtnLayout);
        jpMinimizeBtnLayout.setHorizontalGroup(
            jpMinimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMinimizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpMinimizeBtnLayout.setVerticalGroup(
            jpMinimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMinimizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpTopBar.add(jpMinimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 40, 30));

        jpBg.add(jpTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jlImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/burger-food-logo-design-803831_resized.png"))); // NOI18N
        jpBg.add(jlImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jpText.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("¡Bienvenido/a a BurguerB!");

        jbStartMenu.setBackground(new java.awt.Color(95, 40, 0));
        jbStartMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbStartMenu.setForeground(new java.awt.Color(255, 255, 255));
        jbStartMenu.setText("Iniciar menú");
        jbStartMenu.setBorderPainted(false);
        jbStartMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbStartMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbStartMenuMouseClicked(evt);
            }
        });
        jbStartMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartMenuActionPerformed(evt);
            }
        });

        jbShowMenu.setBackground(new java.awt.Color(43, 0, 0));
        jbShowMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbShowMenu.setForeground(new java.awt.Color(255, 255, 255));
        jbShowMenu.setText("Ver menú");
        jbShowMenu.setBorderPainted(false);
        jbShowMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbShowMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTextLayout = new javax.swing.GroupLayout(jpText);
        jpText.setLayout(jpTextLayout);
        jpTextLayout.setHorizontalGroup(
            jpTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTextLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbStartMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbShowMenu)
                .addContainerGap())
        );
        jpTextLayout.setVerticalGroup(
            jpTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTextLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jpTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbStartMenu)
                    .addComponent(jbShowMenu))
                .addContainerGap(367, Short.MAX_VALUE))
        );

        jpBg.add(jpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbShowMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowMenuActionPerformed
        CreateMenu.getFrames();
    }//GEN-LAST:event_jbShowMenuActionPerformed

    private void jbStartMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbStartMenuActionPerformed

    private void jpTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTopBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jpTopBarMousePressed

    private void jpTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTopBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jpTopBarMouseDragged

    private void jlExitTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitTextMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlExitTextMouseClicked

    private void jlExitTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitTextMouseEntered
        jpExitBtn.setBackground(new java.awt.Color(210,20,4));
        jlExitText.setForeground(Color.white);
    }//GEN-LAST:event_jlExitTextMouseEntered

    private void jlExitTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitTextMouseExited
        jpExitBtn.setBackground(Color.white);
        jlExitText.setForeground(Color.red);
    }//GEN-LAST:event_jlExitTextMouseExited

    private void jlMinimizeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizeTextMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizeTextMouseClicked

    private void jlMinimizeTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizeTextMouseEntered
        jpMinimizeBtn.setBackground(Color.lightGray);
        jlMinimizeText.setForeground(Color.white);
    }//GEN-LAST:event_jlMinimizeTextMouseEntered

    private void jlMinimizeTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizeTextMouseExited
        jpMinimizeBtn.setBackground(Color.white);
        jlMinimizeText.setForeground(Color.black);
    }//GEN-LAST:event_jlMinimizeTextMouseExited

    private void jbStartMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbStartMenuMouseClicked
        CreateMenu menu = new CreateMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbStartMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbShowMenu;
    private javax.swing.JButton jbStartMenu;
    private javax.swing.JLabel jlExitText;
    private javax.swing.JLabel jlImage;
    private javax.swing.JLabel jlMinimizeText;
    private javax.swing.JPanel jpBg;
    private javax.swing.JPanel jpExitBtn;
    private javax.swing.JPanel jpMinimizeBtn;
    private javax.swing.JPanel jpText;
    private javax.swing.JPanel jpTopBar;
    // End of variables declaration//GEN-END:variables
}
